paths:
  raw_data: "data/raw"
  processed_data: "../phase1/data/processed/"
  embeddings: "../phase1/data/processed/embeddings"  # reuse phase1 embeddings directly
  submissions: "data/submissions"
  images: "../phase1/data/raw/fit_dataset_images" # reuse phase1 images


embedding:
  model_name: "paraphrase-multilingual-mpnet-base-v2"
  batch_size: 256
  normalize: true
  max_description_length: 500

faiss:
  k_neighbors: 20
  edge_threshold: 0.85
  use_image: false 
  text_weight: 0.6
  image_weight: 0.4
  n_cells: 400
  n_probe: 20

clustering:
  resolution: 1.0

currency:
  sk: 1.0
  hr: 1.0
  lv: 1.0
  si: 1.0
  gr: 1.0
  it: 1.0
  lt: 1.0
  ee: 1.0
  cz: 0.04
  bg: 0.5112
  hu: 0.0025
  ro: 0.2
  pl: 0.2326
