"""
Fine-tune SentenceTransformer with contrastive loss on product pairs.

Run this on Google Colab (free T4 GPU, ~1-2 hours).

Setup on Colab (run in a cell before this script):
    from google.colab import drive
    drive.mount('/content/drive')
    !pip install sentence-transformers

Upload to Colab before running:
    contrastive_pairs.parquet   (generated by build_pairs.py)

Usage:
    python finetune_embeddings.py

Resuming after a crash:
    Set BASE_MODEL to the latest checkpoint folder, e.g.:
        BASE_MODEL = "/content/drive/MyDrive/adm/phase2/checkpoints/500"
    Set EPOCHS to however many epochs remain.

After training, update configs/default.yaml:
    embedding:
      model_name: "/content/drive/MyDrive/adm/phase2/finetuned-product-encoder"
      (or copy the folder locally and use a local path)

Then re-run:
    python phase2/scripts/extract_embeddings.py
    python phase2/scripts/train_edge_scorer.py
    python phase2/scripts/run.py --validate
"""

import os
import math
import pandas as pd
from torch.utils.data import DataLoader
from sentence_transformers import SentenceTransformer, InputExample, evaluation
from sentence_transformers.losses import MultipleNegativesRankingLoss

# ── Config ─────────────────────────────────────────────────────────────────────

BASE_MODEL   = "paraphrase-multilingual-mpnet-base-v2"
PAIRS_FILE   = "contrastive_pairs.parquet"
BATCH_SIZE   = 64
EPOCHS       = 3
WARMUP_RATIO = 0.1

# All output goes to Drive — survives VM disconnect
DRIVE_DIR  = "/content/drive/MyDrive/adm/phase2"
OUTPUT_DIR = f"{DRIVE_DIR}/finetuned-product-encoder"
CKPT_DIR   = f"{DRIVE_DIR}/checkpoints"

os.makedirs(DRIVE_DIR, exist_ok=True)

# ── Load pairs ─────────────────────────────────────────────────────────────────

print("Loading pairs...")
df = pd.read_parquet(PAIRS_FILE)
print(f"  {len(df):,} positive pairs")

split    = int(len(df) * 0.9)
train_df = df.iloc[:split]
eval_df  = df.iloc[split:]

train_examples = [
    InputExample(texts=[row.text_a, row.text_b])
    for row in train_df.itertuples()
]

# ── Model ──────────────────────────────────────────────────────────────────────
# cache_folder on Drive so re-runs don't re-download 1GB

print(f"Loading base model: {BASE_MODEL}")
model = SentenceTransformer(BASE_MODEL, cache_folder=f"{DRIVE_DIR}/hf_cache")

# ── Loss ───────────────────────────────────────────────────────────────────────

loss = MultipleNegativesRankingLoss(model)

# ── Evaluator ──────────────────────────────────────────────────────────────────

evaluator = evaluation.EmbeddingSimilarityEvaluator(
    sentences1=eval_df["text_a"].tolist(),
    sentences2=eval_df["text_b"].tolist(),
    scores=[1.0] * len(eval_df),
    name="product-pairs",
)

# ── Train ──────────────────────────────────────────────────────────────────────

train_dataloader = DataLoader(train_examples, shuffle=True, batch_size=BATCH_SIZE)
steps_per_epoch  = len(train_dataloader)
warmup_steps     = math.ceil(steps_per_epoch * EPOCHS * WARMUP_RATIO)
ckpt_every       = max(1, steps_per_epoch // 4)  # ~4 checkpoints per epoch

print(f"\nSteps per epoch: {steps_per_epoch}  checkpoint every: {ckpt_every} steps")
print(f"Fine-tuning for {EPOCHS} epochs  (warmup={warmup_steps} steps)...")
print(f"Output:      {OUTPUT_DIR}")
print(f"Checkpoints: {CKPT_DIR}")

model.fit(
    train_objectives=[(train_dataloader, loss)],
    evaluator=evaluator,
    epochs=EPOCHS,
    warmup_steps=warmup_steps,
    output_path=OUTPUT_DIR,
    save_best_model=True,
    evaluation_steps=steps_per_epoch,      # eval once per epoch
    checkpoint_path=CKPT_DIR,
    checkpoint_save_steps=ckpt_every,      # ~4x per epoch to Drive
    checkpoint_save_total_limit=4,
    show_progress_bar=True,
)

print(f"\nDone. Model saved to: {OUTPUT_DIR}")
print(f"Find it in Google Drive: MyDrive/adm/phase2/finetuned-product-encoder/")
